### PR TITLE
fix(local-notifications): Notifications are not generated when using defaults

### LINKED ISSUE #595: [@nativescript/local-notifications] No notifications are displayed when relying on default option values
Since 6.2.0 (https://github.com/NativeScript/plugins/commit/ed5feb9f85135a3d64a86ef8da5b44f344b1698e in particular) the `schedule()` function doesn't show any notification if all optional parameters of the `scheduleOptions` object are omitted. It worked fine with the previous version 6.1.1.

There are two separate problems:

1. By omitting the `at` option, its value now defaults to `-1` instead of `0`: https://github.com/NativeScript/plugins/blob/ed5feb9f85135a3d64a86ef8da5b44f344b1698e/packages/local-notifications/index.android.ts#L207 This causes notifications to never show and there is no error message. The `com.telerik.localnotifications` package expects `0` for notifications that are supposed to be displayed immediately: https://github.com/EddyVerbruggen/nativescript-local-notifications/blob/master/native-src/android/app/src/main/java/com/telerik/localnotifications/NotificationRestoreReceiver.java#L52
  Workaround:
   ```javascript
   at: { getTime: () => 0 } as Date
   ```
2. With the above workaround, the first notification is displayed, but any following notification is not and there's this error message: `Error in LocalNotifications.schedule: TypeError: iconLocation.indexOf is not a function`. This is because the `LocalNotificationsCommon.merge()` function [was rewritten](https://github.com/NativeScript/plugins/blob/ed5feb9f85135a3d64a86ef8da5b44f344b1698e/packages/local-notifications/common.ts#L287) in a way that it modifies one of the objects passed as arguments, as opposed to returning a new object with the merged properties and leaving the argument objects unchanged. Confusingly, the function modifies the `source` argument instead of the `target`. This causes the `LocalNotificationsImpl.defaults` object to be modified [here](https://github.com/NativeScript/plugins/blob/ed5feb9f85135a3d64a86ef8da5b44f344b1698e/packages/local-notifications/index.android.ts#L200).
   You can workaround this issue by passing these two options with their default values explicitly:
   ```javascript
   icon: "res://ic_stat_notify",   
   silhouetteIcon: "res://ic_stat_notify_silhouette",
   ```

### PR DESCRIPTION
**Pull request by CatchABus**
This PR is an attempt to fix #595 along with some cleanup.

### CODE REVIEW

File: packages/local-notifications/index.android.ts [hunk 1]
```diff
@@ -206,45 +213,45 @@ export class LocalNotificationsImpl extends LocalNotificationsCommon implements
...
-
-				LocalNotificationsImpl.ensureID(options);
-
-				options.atTime = options.at ? options.at.getTime() : -1;
-				if (interval) {
-					options.atTime = Date.now() + options.repeatInterval;
+			for (const s of scheduleOptions) {
+				const entry = LocalNotificationsImpl.createScheduleEntry(s);
+				// Some properties should not be inherited by options
+				const nativeOptions: ScheduleNativeOptions = { ...entry, color: undefined, notificationLed: undefined };
```
Comment (PeterStaev) [inline packages/local-notifications/index.android.ts:223]: What is the idea of this extend? Won't this always nullify the properties that are sent by users?

File: packages/local-notifications/index.android.ts [hunk 2]
```diff
@@ -206,45 +213,45 @@ export class LocalNotificationsImpl extends LocalNotificationsCommon implements
...
+					interval = null;
+					ticks = 1;
 				}
 
-				options.icon = LocalNotificationsImpl.getIcon(context, resources, (LocalNotificationsImpl.IS_GTE_LOLLIPOP && options.silhouetteIcon) || options.icon);
-				options.repeatInterval = LocalNotificationsImpl.getIntervalMilliseconds(interval, ticks);
+				nativeOptions.atTime = entry.at ? entry.at.getTime() : 0;
+				nativeOptions.icon = LocalNotificationsImpl.getIcon(context, resources, (LocalNotificationsImpl.IS_GTE_LOLLIPOP && entry.silhouetteIcon) || entry.icon);
+				nativeOptions.repeatInterval = LocalNotificationsImpl.getIntervalMilliseconds(interval, ticks);
+				nativeOptions.color = entry.color.android;
```
Comment (PeterStaev) [inline packages/local-notifications/index.android.ts]: This will crash when no color is sent in options.

File: packages/local-notifications/index.ios.ts [hunk 3]
```diff
@@ -78,88 +78,110 @@ export class LocalNotificationsImpl extends LocalNotificationsCommon implements
...
 			content.subtitle = body ? subtitle : undefined;
 			// On iOS, a notification with no body won't show up, so the subtitle or title will be used in this case as body
 			// instead. If none of them is set, we set it to ' ' and will show up as an empty line in the notification:
 			content.body = body || subtitle || title || ' ';
 
-			content.badge = options.badge;
+			content.badge = entry.badge;
 
-			if (options.sound === undefined || options.sound === 'default') {
+			if (entry.sound == null || entry.sound === 'default') {
```
Comment (PeterStaev) [inline packages/local-notifications/index.ios.ts]: The null check here will fail when default options are used and user doesn't send any `sound`. Whey not simply change to `!options.sound`?

File: packages/local-notifications/index.ios.ts [hunk 4]
```diff
@@ -78,88 +78,110 @@ export class LocalNotificationsImpl extends LocalNotificationsCommon implements
...
+
+			if (entry.interval) {
+				const intervalData = Object.entries(entry.interval)[0] as [ScheduleInterval, number];
+
+				interval = intervalData[0];
+				ticks = intervalData[1];
+			} else {
+				interval = null;
+				ticks = 1;
+			}
```
Comment (PeterStaev) [inline packages/local-notifications/index.ios.ts]: This logic is the same for ios and android. Can't we extract this in a method in common so it can be reused and unified on both places (in case a future change is made)

File: packages/local-notifications/index.ios.ts [hunk 5]
```diff
@@ -204,25 +224,26 @@ export class LocalNotificationsImpl extends LocalNotificationsCommon implements
...
 						}
 					}
-					triggers.forEach(trigger => registerNotification(trigger[0], content, trigger[1], scheduledIds))
 				});
 			}
+
+			registerNotification(entry.id, content, trigger, scheduledIds);
+
+			if (interval && entry.displayImmediately) {
+				const id = LocalNotificationsImpl.generateNotificationID();
```
Comment (PeterStaev) [inline packages/local-notifications/index.ios.ts:221]: Unlike the old logic, won't this generate a new ID. What will happen if I decide to cancel the ID of the original request? To me the old logic would cancel both the immediately scheduled one and the other one that was scheduled with interval.

File: packages/local-notifications/index.ios.ts [hunk 6]
```diff
@@ -235,48 +256,44 @@ export class LocalNotificationsImpl extends LocalNotificationsCommon implements
...
 			}
 			notification.userInfo = userInfoDict;
 
-			switch (options.sound) {
-				case null:
-				case false:
-					break;
-				case undefined:
-				case 'default':
+			if (entry.sound) {
```
Comment (PeterStaev) [inline packages/local-notifications/index.ios.ts]: Fold `undefined` old logic would use default sound, unlike in the rewritten logic. So this should be adjusted to account for no sound sent.

**Review by PeterStaev — CHANGES_REQUESTED** [review]

File: packages/local-notifications/index.android.ts (hunk 1 above)
Comment (CatchABus) [reply packages/local-notifications/index.android.ts:223]: Not at all. The `nativeOptions` object is meant for being sent to the native side as a json string.
In line 223, we mark color and notificationLed as undefined to:
- Prevent them from being read from native lib in case they're not set below (because they're set below)
- Correct type warnings

File: packages/local-notifications/index.ios.ts (hunk 3 above)
Comment (CatchABus) [reply packages/local-notifications/index.ios.ts]: Not at all. In JavaScript, non-strict `null` comparison will check for both `null` and `undefined`.
We can definitely have a falsey check like the one you suggested if we want default sound to always apply in that case.

EDITED: Now I see what you meant. I'll revert that change so that users have the ability to omit sound.

File: packages/local-notifications/index.ios.ts (hunk 5 above)
Comment (CatchABus) [reply packages/local-notifications/index.ios.ts:221]: I don't think it worked for you that way. Perhaps, you're confused.
Even now, immediate notifications have their own unique ID.
See:
https://github.com/NativeScript/plugins/blob/main/packages/local-notifications/index.android.ts#L241
https://github.com/NativeScript/plugins/blob/main/packages/local-notifications/index.ios.ts#L151

File: packages/local-notifications/index.android.ts (hunk 2 above)
Comment (CatchABus) [reply packages/local-notifications/index.android.ts]: Solved

File: packages/local-notifications/index.ios.ts (hunk 3 above)
Comment (CatchABus) [reply packages/local-notifications/index.ios.ts]: Reverted back to old value.

File: packages/local-notifications/index.ios.ts (hunk 4 above)
Comment (CatchABus) [reply packages/local-notifications/index.ios.ts]: Done. Thanks for pointing out.

File: packages/local-notifications/index.ios.ts (hunk 6 above)
Comment (CatchABus) [reply packages/local-notifications/index.ios.ts]: Reverted to using the good old switch statement with the addition of `''` check.

**Review by PeterStaev — APPROVED** [review]
