### ISSUE TITLE
[@nativescript/local-notifications] No notifications are displayed when relying on default option values

### ISSUE THREAD

**Issue by jkatins** [NativeScript/plugins#595]
Since 6.2.0 (https://github.com/NativeScript/plugins/commit/ed5feb9f85135a3d64a86ef8da5b44f344b1698e in particular) the `schedule()` function doesn't show any notification if all optional parameters of the `scheduleOptions` object are omitted. It worked fine with the previous version 6.1.1.

There are two separate problems:

1. By omitting the `at` option, its value now defaults to `-1` instead of `0`: https://github.com/NativeScript/plugins/blob/ed5feb9f85135a3d64a86ef8da5b44f344b1698e/packages/local-notifications/index.android.ts#L207 This causes notifications to never show and there is no error message. The `com.telerik.localnotifications` package expects `0` for notifications that are supposed to be displayed immediately: https://github.com/EddyVerbruggen/nativescript-local-notifications/blob/master/native-src/android/app/src/main/java/com/telerik/localnotifications/NotificationRestoreReceiver.java#L52
  Workaround:
   ```javascript
   at: { getTime: () => 0 } as Date
   ```
2. With the above workaround, the first notification is displayed, but any following notification is not and there's this error message: `Error in LocalNotifications.schedule: TypeError: iconLocation.indexOf is not a function`. This is because the `LocalNotificationsCommon.merge()` function [was rewritten](https://github.com/NativeScript/plugins/blob/ed5feb9f85135a3d64a86ef8da5b44f344b1698e/packages/local-notifications/common.ts#L287) in a way that it modifies one of the objects passed as arguments, as opposed to returning a new object with the merged properties and leaving the argument objects unchanged. Confusingly, the function modifies the `source` argument instead of the `target`. This causes the `LocalNotificationsImpl.defaults` object to be modified [here](https://github.com/NativeScript/plugins/blob/ed5feb9f85135a3d64a86ef8da5b44f344b1698e/packages/local-notifications/index.android.ts#L200).
   You can workaround this issue by passing these two options with their default values explicitly:
   ```javascript
   icon: "res://ic_stat_notify",   
   silhouetteIcon: "res://ic_stat_notify_silhouette",
   ```

**Comment by insytes** [comment]
My fault, I will pick this up and fix these 2 issues.

**Comment by PeterStaev** [comment]
So 3 months and this critical problem has not been fixed. And in general how are PRs tested/approved when a "minor" version increases has so much code rewritten with break in old logic and buggy code???

**Comment by CatchABus** [comment]
> So 3 months and this critical problem has not been fixed. And in general how are PRs tested/approved when a "minor" version increases has so much code rewritten with break in old logic and buggy code???

I think that update was meant to add new functionality while maintaining the old one, that's why it was released in a minor version.
We understand the inconvenience this has caused you and I think I can proceed on creating a PR today if it's ok with everyone.
